captcha_agent:
  model: gemini-2.5-pro
  base_url: https://api.tu-zi.com/v1
  api_key: sk-jsiE3Le9Dh8V7h1UJ202x15uPyIoK909FkaFX8HmAKC0h1ha

autobrowser_agent:
  model: gemini-2.5-pro
  base_url: https://api.tu-zi.com/v1
  api_key: sk-jsiE3Le9Dh8V7h1UJ202x15uPyIoK909FkaFX8HmAKC0h1ha

login_agent:
  init:
    # url: https://captcha6.scrape.center/
    url: https://www.reddit.com/login/
    headless: false
    wait_time: 3
  login:
    username: agentspro0bot
    password: ubi2future
    username_selector: '://input[@name="username"]'
    password_selector: 'xpath://input[@name="password"]'
    button_selector: 'xpath://button[contains(@class, "login")]'
    auto_handle_captcha: true